apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: project1
spec:
  containers:
    - name: hello-world
      image: busybox
      env:
        - name: HELLO_SECRET
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: HELLO_SECRET
